config/routes.rb
NewsSniffer::Application.routes.draw do
  get 'health/check'

  get 'articles/:article_id/diff/:version_b/:version_a' => 'versions#diff', :as => :diff
  resources :versions do
    collection do
      get :search
    end
  end

  resources :articles, :controller => :news_articles do
    collection do
      get :search
    end

    resources :versions
  end

  get '/' => 'versions#index'
  get '/:controller(/:action(/:id))'
end

app/models/news_article.rb
#    News Sniffer
#    Copyright (C) 2007-2016 John Leach
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

# A NewsArticle represents an article that usually has one or many versions.
class NewsArticle < ActiveRecord::Base

  has_many :versions, :class_name => 'NewsArticleVersion', :dependent => :destroy, :autosave => true
  validates_length_of :title, :minimum => 5
  validates_presence_of :source # bbc, guardian, independent?
  validates_presence_of :guid, :parser
  validates_uniqueness_of :guid
  validates_length_of :guid, :maximum => 250
  validates_length_of :url, :minimum => 10, :maximum => 250

  attr_readonly :versions_count

  before_validation :set_initial_next_check_period, :unless => :next_check_after?

  scope :due_check, lambda { order('next_check_after asc').where(["check_period < ? AND next_check_after < ?", 40.days.to_i, Time.now.utc]) }

  # Retrieve the news page from the web, parse it and create a new
  # version if necessary, returning the saved NewsArticleVersion
  def update_from_source
    if parser
      page = eval("WebPageParser::#{parser}").new(:url => url)
    else
      page = WebPageParser::ParserFactory.parser_for(:url => url)
    end
    if page
      begin
        update_from_page(page)
      rescue StandardError => e
        reload
        set_next_check_period
        logger.error("article_id=#{id} source=#{source} retrieval error #{e.inspect} #{e.to_s} next_check_after=#{next_check_after}")
        save!
      end
    else
      logger.warn("article_id=#{id} source=#{source} status=unknown_parser parser=#{parser}")
    end
  end

  # Create a new version from the parsed html if it changed, returning
  # the saved NewsArticleVersion
  def update_from_page(page)
    if page.hash.nil? or page.hash == latest_text_hash
      # Content didn't change
      set_next_check_period
      logger.info("article_id=#{id} status=unchanged next_check_after=#{next_check_after}")
      save
      nil
    elsif count_versions_by_hash(page.hash) > 1
      set_next_check_period
      logger.warn("article_id=#{id} status=flipflopping next_check_after=#{next_check_after}")
      save
      nil
    else
      # Content changed!
      version = versions.build
      version.populate_from_page(page)
      begin
        self.with_lock('LOCK IN SHARE MODE') do
          self.title = page.title
          reset_next_check_period
          version.save! # explicitly saved to raise more useful validation exception
          save!
        end
      rescue ActiveRecord::RecordInvalid => e
        reload
        set_next_check_period
        logger.error("article_id=#{id} status=RecordInvalid error=#{e} next_check_after=#{next_check_after}")
        save!
        return nil
      rescue Mysql2::Error=> e
        # Back off retrying articles that db won't accept for somer reason
        # such as bad utf, too large data, etc. No point trying forever.
        set_next_check_period
        logger.error("article_id=#{id} status=Mysql2::Error error=#{e} next_check_after=#{next_check_after}")
        save!
        return nil
      rescue ActiveRecord::StatementInvalid => e
        # Back off retrying articles that db won't accept for somer reason
        # such as bad utf, too large data, etc. No point trying forever.
        set_next_check_period
        logger.error("article_id=#{id} status=StatementInvalid error=#{e}  next_check_after=#{next_check_after}")
        save!
        return nil
      end
      logger.info("article_id=#{id} status=new_version version_id=#{version.id}")
      version
    end
  end

  def latest_text_hash
    versions.order('version desc').select(:text_hash).first.try(:text_hash)
  end

  def count_versions_by_hash(count_hash)
    versions.where(:text_hash => count_hash).count
  end

  private

  def set_next_check_period
    if check_period == 0
      self.check_period = 30.minutes 
    else
      self.check_period = (check_period * 1.2).round
    end
    self.next_check_after = Time.now + self.check_period
  end

  def reset_next_check_period
    self.check_period = 30.minutes
    self.next_check_after = Time.now + self.check_period
  end

  def set_initial_next_check_period
    self.check_period = 0
    self.next_check_after = Time.now
  end
end

app/controllers/news_articles_controller.rb
#    News Sniffer
#    Copyright (C) 2007-2008 John Leach
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

#
class NewsArticlesController < ApplicationController
  layout 'newsniffer'

  def index
    @title = "Latest news articles"
    @articles = NewsArticle.order('news_articles.id desc').includes(:versions).paginate :page => params[:page] || 1,
      :per_page => 20
  end

  def show
    @article = NewsArticle.find(params[:id])
    @versions = @article.versions.order('version asc').select("id, version, title, created_at")
    respond_to do |format|
      format.html
      format.rss { render :content_type => 'text/xml', :layout => false }
    end
  end

  def health
    sources = NewsArticle.group(:source).where('versions_count > 0').where(['created_at > ?', Time.now-1.day]).count
    health = sources.detect { |k,v| v < 5 } ? 'WARNING' : 'OK'
    render :json => [health, sources]
  end

end

app/helpers/news_articles_helper.rb
#    News Sniffer
#    Copyright (C) 2007-2008 John Leach
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

#
module NewsArticlesHelper
end

app/views/news_articles/index.html.erb
<h2>News Articles</h2>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Versions</th>
      <th>Source</th>
    </tr>
  </thead>
  <tbody>
  <% @articles.each do |article| %>
    <tr>
    <% if article.versions_count > 1 %>
      <td>
        <%= link_to h(truncate(article.title, :length => 75)), 
                      diff_url(article, article.versions[-2].version, article.versions[-1].version),
                        :title => "#{h(article.title)}, first published #{article.created_at}" %>
      </td>
    <% else %>
      <td>
        <span title="<%= "#{h(article.title)}, first published #{article.created_at}" %>">
          <%= h(truncate(article.title, :length => 75)) %>
        </span>
      </td>
    <% end %>
      <td class="version"><%= article.versions_count %></td>
      <td>
        <small><%= article.source %></small>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<hr />

<%= will_paginate @articles %>

app/views/news_articles/show.html.erb
<% content_for :head do %>
    <%= auto_discovery_link_tag(:rss, article_url(@article, :format => :rss), :title => "RSS feed of versions of this article") %>
    <link href="<%= @article.url %>" rel="external alternate author" title="Original article"/>
	<meta name="generator" content="<%= @article.parser %>"/>
<% end %>
<% @title = "'#{@article.title}' article at News Sniffer" %>
<h1><%= @article.title %></h1>

<p>This article is from the source '<cite><%= @article.source %></cite>' and was first published or seen
on <time datetime='<%= @article.created_at.iso8601 %>'><%= @article.created_at.utc.to_s(:long) %> (UTC)</time>.

<% if @article.next_check_after.nil? %>
It will not be checked again for changes.
<% elsif @article.next_check_after < (Time.now - 40.days) %>
It last changed over 40 days ago and won't be checked again for changes.
<% else %>
The next check for changes will be <time datetime='<%= @article.next_check_after.iso8601 %>'><%= @article.next_check_after.to_s(:long) %></time>
<% end %>

<p>You can find the current article at its original source at <cite class="article_url"><%= link_to @article.url, @article.url, :rel => "alternate external author" %></cite></p>

<p>The article has changed <var><%= @versions.size %></var> times. There is an <%= link_to 'RSS feed of changes', article_url(@article, :format => :rss), :class => 'feed rss', :rel => "alternate" %> available.</p>

<table>
<tr>
  <th class="version">Version</th>
  <th class="created_at">Created at</th>
	<th class="period">Period</th>
  <th class="title">Title</th>
</tr>
<% @versions.each do |version| %>
<tr>
<td>
  <%= link_to version.version, article_version_url(@article, version) %>
<td>
  <%= version.created_at.to_s(:long) %>
</td>
<td>
  <% if @prev_date %>
    <%= distance_of_time_in_words(@prev_date, version.created_at) %> later
  <% end %>
<td>
	<%= h(version.title) %>
</td>
</tr>
<% @prev_date = version.created_at %>
<% end%>
</table>