config/routes.rb
NewsSniffer::Application.routes.draw do
  get 'health/check'

  get 'articles/:article_id/diff/:version_b/:version_a' => 'versions#diff', :as => :diff
  resources :versions do
    collection do
      get :search
    end
  end

  resources :articles, :controller => :news_articles do
    collection do
      get :search
    end

    resources :versions
  end

  get '/' => 'versions#index'
  get '/:controller(/:action(/:id))'
end

app/controllers/versions_controller.rb
require "diff_html"
class VersionsController < ApplicationController

  def index
    if params.has_key? :q
      redirect_to search_versions_url(:q => params[:q]), :status => :moved_permanently
      return
    end
    @versions = NewsArticleVersion.includes(:news_article).order('news_article_versions.id desc').paginate(:per_page => 16, :page => params[:page]  || 1)
    respond_to do |format|
      format.html
      format.rss { render :content_type => 'text/xml', :layout => false }
    end
  end

  def search
    @search = params[:q].to_s
    @versions = NewsArticleVersion.xapian_search(@search, :per_page => 16, :collapse => :news_article_id,
                                                 :page => params[:page] || 1)
    respond_to do |format|
      format.html { render :index }
      format.rss { render :index, :content_type => 'text/xml', :layout => false }
    end
  end

  def show
    if params[:article_id]
      @article = NewsArticle.find(params[:article_id])
      @version = @article.versions.find(params[:id])
    else
      @version = NewsArticleVersion.find(params[:id])
      @article = @version.news_article
    end
    if @article.hidden?
      render :text => "This article cannot be shown for legal reasons", :status => 410
    else
      @versions = @article.versions.order('version asc')
    end
  end

  def diff
    @article = NewsArticle.find(params[:article_id])
    @versions = @article.versions.order('version asc')
    @va = @article.versions.find_by_version!(params[:version_a])
    @vb = @article.versions.find_by_version!(params[:version_b])

    @diff = HTMLDiff::diff(@vb.text.split(/\n/), @va.text.split(/\n/))
    if @article.hidden?
      render :text => "This article cannot be shown for legal reasons", :status => 410
    end
  rescue ActiveRecord::RecordNotFound => e
    render :status => 404, :text => e.message
  end

end

app/helpers/versions_helper.rb
module VersionsHelper
end

app/views/versions/_pagination.html.erb
<div class="version_list pagination">
	<% if @vb.version == 0 %>
		<span class="prev_page disabled">Previous version</span>
	<% else %>
		<%= link_to 'Previous version', { :action => 'diff',
	 	:version_a => @vb.version,
	 	:version_b => @vb.version - 1 }, :class => 'prev_page' %>
	<% end %>

	<% @versions.each do |version| %>
	<% next if version.version == 0 %>
		<% if version.version == @va.version %>
			<span class="current"><%= version.version %></span>
		<% else %>
			<%= link_to version.version, 
			diff_url(@article, version.version - 1, version.version),
			:title => version.created_at.to_s(:long) %>
		<% end %>
	<% end %>

	<% if @va.version + 1 == @article.versions_count %>
		<span class="next_page disabled">Next version</span>
	<% else %>
		<%= link_to 'Next version', { :action => 'diff',
		  :version_a => @va.version + 1,
		  :version_b => @va.version }, :class => 'next_page' %>
	<% end %>
</div> 

app/views/versions/diff.html.erb
<% content_for :head do %>
	 <%= auto_discovery_link_tag(:rss, article_url(@article, :format => :rss), :title => "RSS feed of versions of this article") %>
	 <link href="<%= @article.url %>" rel="external alternate author" title="Original article"/>
	 <meta name="generator" content="<%= @article.parser %>"/>
<% end %>

<% @title = "'#{@article.title}' diff viewer (#{@vb.version}/#{@va.version})" %>

<div class="article-info">
	<p>This article is from the source '<cite><%= @article.source %></cite>' and was first published or seen
	on <time datetime='<%= @article.created_at.iso8601 %>'><%= @article.created_at.utc.to_s(:long) %> (UTC)</time>.

	<% if @article.next_check_after.nil? %>
		It will not be checked again for changes.
	<% elsif @article.next_check_after < (Time.now - 40.days) %>
		It last changed over 40 days ago and won't be checked again for changes.
	<% else %>
		The next check for changes will be <time datetime='<%= @article.next_check_after.iso8601 %>'><%= @article.next_check_after.to_s(:long) %></time>
	<% end %>
	</p>

	<p>You can find the current article at its original source at <cite class="article_url"><%= link_to @article.url, @article.url, :rel => "alternate external author" %></cite></p>

	<p>The article has changed <var><%= @versions.size %></var> times. There is an <%= link_to 'RSS feed of changes', article_url(@article, :format => :rss), :class => 'feed rss', :rel => "alternate" %> available.</p>
</div>

<%= render "pagination" %>

<table class="version_diff">
	<thead>
		<tr>
			<th class="version"><small>Version <%= @vb.version %></small></th>
			<th class="version"><small>Version <%= @va.version %></small></th>
		</tr>
		<tr id="title">
		<% if @va.title == @vb.title %>
			<th class="title"><%= h @vb.title %></th>
			<th class="title"><%= h @va.title %></th>
		<% else %>
			<th class="title"><del><%= h @vb.title %></del></th>
			<th class="title"><ins><%= h @va.title %></ins></th>
		<% end %>
		</tr>
		<tr>
			<th class="time"><time datetime="<%= @vb.created_at.iso8601 %>"><%= @vb.created_at %></time></th>
			<th class="time">
				<time datetime="<%= @va.created_at.iso8601 %>">
				<%= @va.created_at %>
				</time> 
				(<%= distance_of_time_in_words(@vb.created_at, @va.created_at) %> <%= @va.created_at > @vb.created_at ? "later" : "earlier" %>)
			</th>
		</tr>
	</thead>
<%= raw @diff %>
</table>

<%= render "pagination" %>

app/views/versions/index.html.erb
<% content_for :head do %>
<%= auto_discovery_link_tag(:rss, versions_path(:format => :rss), :title => "RSS feed of all news article versions") %>
<% end %>

<div class="wrap">

<div id="search">
<%= form_tag search_versions_url, :method => :get do  %>
   <%= text_field_tag 'q', @search, :class => 'searchbox', :size => 40 %>
   <%= submit_tag ' Search ' %>
<% end %>
</div>

<% if @search %>
<% if @versions.empty? %>
  <p>Your search did not match any versions.</p>
<% else %>
  <p>About <%= number_with_delimiter @versions.total_entries %> results.</p>
<% end %>
<% end %>

<table class="versions">
	<thead>
		<tr>
			<th class="title">News Article Title</th>
			<th class="version">Version</th>
			<th class="source">Source</th>
	    	<th class="created_at">Discovered</th>
		</tr>
	</thead>
	<tbody>
		<% @versions.each do |version| %>
		<tr>
			<td class="title">
				<% if version.version > 0 %>
				<%= link_to h(truncate(version.title, :length => 120)),
				diff_url(version.news_article.id, version.version - 1, version.version),
				:class => "version_title" %>
				<% elsif version.news_article.versions_count > 1 %>
		        <%= link_to h(truncate(version.title, :length => 120)),
				diff_url(version.news_article.id, version.version, version.version + 1),
				:class => "version_title" %>
		        <% else %>
				<%= link_to h(truncate(version.title, :length => 120)), article_url(version.news_article),
		        :class => "version_title" %>
				<% end %>
			</td>
			<td class="version">
				<%= version.version %>
			</td>
			<td class="source">
				<cite title="<%= version.url %>"><%= version.news_article.source %></cite>
			</td>
			<td class="created_at">
				<time datetime="<%= version.created_at.iso8601 %>">
				<% if version.created_at < Time.now - 2.hours %>
				<%= version.created_at.strftime("%d %b %Y, %H:%M") %>
				<% else %>
				<%= distance_of_time_in_words(version.created_at, Time.now) %> ago
				<% end %>
			  </time>
			</td>
		</tr>
		<% end %>
	</tbody>
</table>
<%= will_paginate @versions, :next_label => "Next", :prev_label => "Previous" %>

</div>

app/views/versions/show.html.erb
<% content_for :head do %>
<meta name="robots" content="noindex,noarchive">
<link href="<%= @version.news_article.url %>" rel="external alternate author" title="Original article"/>
<meta name="generator" content="<%= @version.news_article.parser %>"/>
<% end %>

<h1><%= @version.title %></h1>

<table>
	<tr>
		<td>
			<p><%= link_to @version.news_article.url, @version.news_article.url %></p>
			<p>Version <%= @version.version %> of <%= @versions.size %>.</p>
			<% @version.text.split("\n").each do |p| %>
			<p><%= p %></p>
			<% end %>
		</td>
	</tr>
</table>