config/routes.rb
NewsSniffer::Application.routes.draw do
  get 'health/check'

  get 'articles/:article_id/diff/:version_b/:version_a' => 'versions#diff', :as => :diff
  resources :versions do
    collection do
      get :search
    end
  end

  resources :articles, :controller => :news_articles do
    collection do
      get :search
    end

    resources :versions
  end

  get '/' => 'versions#index'
  get '/:controller(/:action(/:id))'
end

app/views/layouts/newsniffer.html.erb
<!DOCTYPE html>
<html>
<head>
  	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	  <title><%= h(@title) + " - " if @title -%>News Sniffer</title>
	  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= yield :head %>
    <script src="//code.jquery.com/jquery-3.1.0.slim.min.js" integrity="sha256-cRpWjoSOw5KcyIOaZNo4i6fZ9tKPhYYb6i5T9RSVJG8=" crossorigin="anonymous"></script>
	  <%= javascript_include_tag "application" %>
</head>
<body>
	<header>
		<div id="header" class="header">
			<div class="logo-head">
				<a href="/"><img src="/images/newsniffer-text.png" alt="News Sniffer" class="logo" id="logo" /></a>
			</div>
			<div class="toggle-nav">
	            <span class="bar"></span>
	            <span class="bar"></span>
	            <span class="bar"></span>
             </div>
			<nav class="navigation">
				<ul id="nav" class="menu">
					<li><%= link_to 'News Article Revisions', versions_url, :title => 'News article Revisions', :class => controller.controller_name == "versions" ? "selected" : "" %></li>
					<li><a href="/blog/">Blog</a></li>
					<li><%= link_to 'About', '/blog/about'%></li>
				</ul>
			</nav>
		</div>
	</header>
	
	<div id="content" class="content">
		<% if flash[:notice] %>
			<div id="notice"><%= flash[:notice] %></div>
		<% end -%>
		<% if flash[:error] %>
			<div id="error"><%= flash[:error] %></div>
		<% end -%>

	<%= yield %>
	</div>

	<footer>
		<div id="footer">
			<% cache(:footer_stats, :expires_in => 6.hours) do %>
				<p>Currently monitoring <%= number_with_delimiter(NewsArticle.count, :separator => ",") %> news articles 
				with <%= number_with_delimiter(NewsArticleVersion.count, :separator => ",") %> different versions.</p>
			<% end %>
		</div>
	</footer>
</body>
</html>